{{- if .Values.foundryvtt.username.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  adminPassword: {{ default "admin" ( ternary .Values.foundryvtt.adminPassword.value .Values.foundryvtt.adminKey true) | b64enc }}
  {{- if .Values.foundryvtt.username.value }}
  username: {{ .Values.foundryvtt.username.value | b64enc }}
  {{- end }}
  {{- if .Values.foundryvtt.password.value }}
  password: {{ .Values.foundryvtt.password.value | b64enc }}
  {{- end }}
  {{- if .Values.foundryvtt.licenseKey.value }}
  licenseKey: {{ .Values.foundryvtt.licenseKey.value | b64enc }}
  {{- end }}
{{- end }}

---
{{- if .Values.selfsigned.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-signed
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: {{ .Values.selfsigned.cert | b64enc }}
  tls.key: {{ .Values.selfsigned.key | b64enc }}
type: kubernetes.io/tls
{{- end }}

---
{{- if eq .Values.foundryvtt.s3.enabled "file" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-aws
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-credentials.json: {{ printf "{\"accessKeyId\": \"%s\", \"secretAccessKey\": \"%s\", \"region\": \"%s\", \"endpoint\": \"%s\" }" .Values.foundryvtt.s3.accessKeyId .Values.foundryvtt.s3.secretAccessKey .Values.foundryvtt.s3.region .Values.foundryvtt.s3.endpoint | b64enc }}
{{- end }}

---
{{- if .Values.foundryvtt.turnConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-turn-configs
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  turnConfigs.json: {{ toJson .Values.foundryvtt.turnConfigs | b64enc }}
{{- end }}
